services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    ports:
      - "6333:6333"
      - "6343:6334"


  redis:
    image: redis:latest
    container_name: redis_rag
    ports:
      - "6379:6379"